#include "..\MainInclude.h"

CBaseClientState*		g_pClientState;
IBaseClientDll*			g_pClient;
IClientModeShared*		g_pClientMode;
IClientEntityList*		g_pClientEntList;
ICVar*					g_pCvar;
IInput*					g_pInput;
IInputSystem*			g_pInputSystem;
IEngineClient*			g_pEngine;
IEngineTrace*			g_pEngineTrace;
IGameEventManager2*		g_pGameEventManager;
IVModelInfo*			g_pVModelInfo;
ILocalize*				g_pLocalize;
IMaterialSystem*		g_pMaterialSystem;
IMaterial*				g_pMaterial;
IGlobalVarsBase*		g_pGlobalVarsBase;
ISurface*				g_pSurface;
IVPanel*				g_pVPanel;
IVModelRender*			g_pVModelRender;
IVRenderView*			g_pVRenderView;